version: '3'
services:
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: raynito
      POSTGRES_PASSWORD: Rayne210781
    ports:
      - 5431:5431
    expose:
      - 5431
    command:
      - p 5431